### ISSUE TITLE
Add support for sorting and filtering based upon relationship attributes

### ISSUE THREAD

**Issue by ghost** [limoncello-php/app#17]
It would be nice to add support for sorting and filtering based upon relationship attributes.

**Comment by neomerx** [comment]
That's possible. Will require attention to details but possible.

There are 2 major parts
- Syntax and syntax parser for such requests
- Actual SQL builder

The SQL builder should consider 3 types of relationships that exists
- belongsTo
- hasMany
- belongsToMany

belongsTo and hasMany would require JOINing 1 table. The tricky part is aliasing those tables. However it's already done for belongsToMany so nothing to reinvent here. It just needs to be carefully copied.

belongsToMany currently joins only intermediate table (as we search only by IDs). If full attribute search it would require adding next (actual resource) table and search within it. Again not rocket science but requires attention.

If you started it I would help with it otherwise it would be in 'backlog' for a while.

**Comment by ghost** [comment]
yes. I have already done the part 'belongsTo' of sorting in my local forked copy.

I am editing the the part of QueryParameterParser, SortParameterInterface and SortParameter in neomerx/json-api and Respository in limoncello-php/json-api.

I think it would be good if official repository supports it.

**Comment by ngantingon** [comment]
`                if (strpos($param, '.') === false) {
                    $isDesc = false;
                    empty($param) === false ?
                        $isDesc = ($param[0] === '-') : E::throwException(new E([], E::HTTP_CODE_BAD_REQUEST));
                    $sortField = ltrim($param, '+-');
                    empty($sortField) === false ?: E::throwException(new E([], E::HTTP_CODE_BAD_REQUEST));
                    $sortParams[] = $this->factory->createSortParam($sortField, $isDesc === false);
                } else {
                    $_param = explode('.', $param);
                    $isDesc = false;
                    empty($_param[0]) === false ?
                        $isDesc = ($_param[0][0] === '-') : E::throwException(new E([], E::HTTP_CODE_BAD_REQUEST));
                    $sortField = ltrim($_param[0], '+-');
                    $sortAttribute = $_param[1];
                    empty($sortField === false) ?: E::throwException(new E([], E::HTTP_CODE_BAD_REQUEST));
                    $sortParams[] = $this->factory->createSortParam($sortField, $isDesc === false, $sortAttribute);
                }`

**Comment by ngantingon** [comment]
[https://github.com/ngantingon/json-api/commit/2b07fe663892cf8f993be79a5e257d739fc85145](url)

**Comment by ghost** [comment]
these are the part i edited:

> ```
> protected function getSortParameters(array $parameters)
> {
>     $sortParams = null;
>     $sortParam = $this->getStringParamOrNull($parameters, self::PARAM_SORT);
>     if ($sortParam !== null) {
>         foreach (explode(',', $sortParam) as $param) {
>             if (strpos($param, '.') === false) {
>                 $isDesc = false;
>                 empty($param) === false ?
>                     $isDesc = ($param[0] === '-') : E::throwException(new E([], E::HTTP_CODE_BAD_REQUEST));
>                 $sortField = ltrim($param, '+-');
>                 empty($sortField) === false ?: E::throwException(new E([], E::HTTP_CODE_BAD_REQUEST));
>                 $sortParams[] = $this->factory->createSortParam($sortField, $isDesc === false);
>             } else {
>                 $isDesc = false;
>                 list($relationship, $relationshipAttribute) = explode('.', $param);
>                 empty($relationship) === false ?
>                     $isDesc = ($relationship[0] === '-') : E::throwException(new E([], E::HTTP_CODE_BAD_REQUEST));
>                 $sortField = ltrim($relationship, '+-');
>                 $sortRelationshipAttribute = $relationshipAttribute;
>                 empty($sortField === false) ?: E::throwException(new E([], E::HTTP_CODE_BAD_REQUEST));
>                 $sortParams[] = $this->factory->createSortParam($sortField, $isDesc === false, $sortRelationshipAttribute);
>             }
>         }
>     }
>     return $sortParams;
> }
> ```

```
public function applySorting(QueryBuilder $builder, $modelClass, array $sortParams)
{
    $table = $this->getTableName($modelClass);
    $quotedTable = $this->buildTableName($table);
    $modelSchemes = $this->getModelSchemes();
    foreach ($sortParams as $sortParam) {
        /** @var SortParameterInterface $sortParam */
        $column = null;
        if ($sortParam->isIsRelationship() === false) {
            $column = $this->buildTableColumnName($table, $sortParam->getName());
        } elseif ($sortParam->getRelationshipType() === RelationshipTypes::BELONGS_TO) {
            if ($sortParam->getRelationshipAttribute() !== null) {
                $foreignKey = $modelSchemes->getForeignKey($modelClass, $sortParam->getName());
                list($reverseClass, $reverseName) = $modelSchemes->getReverseRelationship($modelClass, $sortParam->getName());
                $sortingTable = $modelSchemes->getTable($reverseClass);
                $reversePk = $modelSchemes->getPrimaryKey($reverseClass);
                $aliased = "{$sortingTable}{$this->getNewAliasId()}";
                $joinCondition = "{$this->buildTableColumnName($table, $foreignKey)}={$this->buildTableColumnName($aliased, $reversePk)}";
                $builder->innerJoin(
                    $quotedTable,
                    $this->buildTableName($sortingTable),
                    $aliased,
                    $joinCondition
                );
                $column = $this->buildTableColumnName($aliased, $sortParam->getRelationshipAttribute());
            } else {
                $column = $this->buildTableColumnName($table, $modelSchemes->getForeignKey($modelClass, $sortParam->getName()));
            }
        }

        if ($column !== null) {
            $builder->addOrderBy(
                $column,
                $sortParam->isAscending() === true ? 'ASC' : 'DESC'
            );
        }
    }
}
```

**Comment by neomerx** [comment]
Filtering by IDs in relationships was added. Filtering by other attributes in relationships as an idea was moved to `projects` of the framework https://github.com/limoncello-php/framework/projects/5
