### ISSUE TITLE
validating $toManyRules throws DriverException and PDOException

### ISSUE THREAD

**Issue by ghost** [limoncello-php/app#18]
UserValidator:

     .....
        $toManyRules    = [
            Schema::REL_USER_ENTRIES => $this->userEntryId(),
        ];
     .....
        list (, $attrCaptures, $toManyCaptures) =
            $this->assert($schema, $json, $idRule, $attributeRules, $toOneRules, $toManyRules);

     .....
    private function userEntryId()
    {
        return $this->dbId(UserEntry::TABLE_NAME, UserEntry::FIELD_ID);
    }

UsersTest:

     .....

    public function testCreateAndDelete()
    {
        $this->setPreventCommits();
        $authHeaders = $this->createAdminAuthHeaders();

        // Note you can save `belongsTo` relationships on creation (`belongsToMany` is also supported).
        //
        // `hasMany` could not be saved by it nature as it requires
        // saving additional resources (we can return ID for only 1 created resource per HTTP request).
        $body = <<<EOT
        {
            "data": {
                "type": "users",
                "id"  : null,
                "attributes": {
                    "first-name"     : "TAI MAN",
                    "last-name"      : "CHAN",
                    "initials"       : "TMC",
                    "email"          : "tm.chan@company.ltd",
                    "password"       : "password"
                },
                "relationships": {
                    "role": {
                        "data": { "type": "roles", "id": "3" }
                    },
                    "user-status": {
                        "data": { "type": "user-statuses", "id": "1" }
                    },
                    "user-entries": {
                        "data": [
                            { "type": "user-entries", "id": "1" },
                            { "type": "user-entries", "id": "2" }
                        ]
                    }
                }
            }
        }
EOT;
        try {
            $response = $this->postJson(self::API_URI, $body, $authHeaders);
            $this->assertEquals(201, $response->getStatusCode());
            $this->assertNotEmpty($resource = json_decode((string)$response->getBody()));

            // index of created resource
            $index = $resource->data->id;

            // check it was actually saved in database
            $this->assertEquals(200, $this->get(self::API_URI . "/$index")->getStatusCode());

            // delete
            $this->assertEquals(204, $this->delete(self::API_URI . '/' . $index, [], $authHeaders)->getStatusCode());

            // check resource deleted
            $this->assertEquals(404, $this->get(self::API_URI . "/$index")->getStatusCode());
        } catch (JsonApiException $e) {
            print_r($e->getErrors());
        }
    }

     .....

"testCreateAndDelete" throws:

root:/app# ./vendor/bin/phpunit --filter=testCreateAndDelete UsersTest ./tests/UsersTest.php
PHPUnit 5.6.1 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.0.12
Configuration: /app/phpunit.xml

E                                                                   1 / 1 (100%)

Time: 1.14 seconds, Memory: 8.00MB

There was 1 error:

1) Tests\UsersTest::testCreateAndDelete
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `` (``, created_at) VALUES(?, ?)' with params ["1", "2016-11-02 11:53:49"]:

SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''

/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115
/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:128
/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:996
/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
/app/vendor/limoncello-php/json-api/src/Api/Crud.php:298
/app/vendor/limoncello-php/json-api/src/Api/Crud.php:392
/app/vendor/limoncello-php/json-api/src/Api/Crud.php:301
/app/app/Api/UsersApi.php:40
/app/vendor/limoncello-php/json-api/src/Http/BaseController.php:86
/app/vendor/limoncello-php/core/src/Application/Application.php:304
/app/app/Authorization/Middleware/AuthenticationRequired.php:31
/app/vendor/limoncello-php/core/src/Application/Application.php:362
/app/app/Authentication/Middleware/TokenAuthentication.php:48
/app/vendor/limoncello-php/core/src/Application/Application.php:362
/app/vendor/limoncello-php/json-api/src/Http/Cors/CorsMiddleware.php:49
/app/vendor/limoncello-php/core/src/Application/Application.php:362
/app/vendor/limoncello-php/core/src/Application/Application.php:172
/app/tests/AppWrapper.php:73
/app/vendor/limoncello-php/core/src/Application/Application.php:132
/app/vendor/limoncello-php/testing/src/PhpUnitTestCase.php:96
/app/tests/TestCase.php:140
/app/tests/UsersTest.php:116

Caused by
Doctrine\DBAL\Driver\PDOException: SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''

/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93
/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:987
/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
/app/vendor/limoncello-php/json-api/src/Api/Crud.php:298
/app/vendor/limoncello-php/json-api/src/Api/Crud.php:392
/app/vendor/limoncello-php/json-api/src/Api/Crud.php:301
/app/app/Api/UsersApi.php:40
/app/vendor/limoncello-php/json-api/src/Http/BaseController.php:86
/app/vendor/limoncello-php/core/src/Application/Application.php:304
/app/app/Authorization/Middleware/AuthenticationRequired.php:31
/app/vendor/limoncello-php/core/src/Application/Application.php:362
/app/app/Authentication/Middleware/TokenAuthentication.php:48
/app/vendor/limoncello-php/core/src/Application/Application.php:362
/app/vendor/limoncello-php/json-api/src/Http/Cors/CorsMiddleware.php:49
/app/vendor/limoncello-php/core/src/Application/Application.php:362
/app/vendor/limoncello-php/core/src/Application/Application.php:172
/app/tests/AppWrapper.php:73
/app/vendor/limoncello-php/core/src/Application/Application.php:132
/app/vendor/limoncello-php/testing/src/PhpUnitTestCase.php:96
/app/tests/TestCase.php:140
/app/tests/UsersTest.php:116

Caused by
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''

/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:987
/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
/app/vendor/limoncello-php/json-api/src/Api/Crud.php:298
/app/vendor/limoncello-php/json-api/src/Api/Crud.php:392
/app/vendor/limoncello-php/json-api/src/Api/Crud.php:301
/app/app/Api/UsersApi.php:40
/app/vendor/limoncello-php/json-api/src/Http/BaseController.php:86
/app/vendor/limoncello-php/core/src/Application/Application.php:304
/app/app/Authorization/Middleware/AuthenticationRequired.php:31
/app/vendor/limoncello-php/core/src/Application/Application.php:362
/app/app/Authentication/Middleware/TokenAuthentication.php:48
/app/vendor/limoncello-php/core/src/Application/Application.php:362
/app/vendor/limoncello-php/json-api/src/Http/Cors/CorsMiddleware.php:49
/app/vendor/limoncello-php/core/src/Application/Application.php:362
/app/vendor/limoncello-php/core/src/Application/Application.php:172
/app/tests/AppWrapper.php:73
/app/vendor/limoncello-php/core/src/Application/Application.php:132
/app/vendor/limoncello-php/testing/src/PhpUnitTestCase.php:96
/app/tests/TestCase.php:140
/app/tests/UsersTest.php:116

ERRORS!
Tests: 1, Assertions: 2, Errors: 1.

**Comment by neomerx** [comment]
You haven't posted full example so I can only guess. I think you probably didn't specify table name for model
![image](https://cloud.githubusercontent.com/assets/10420662/19975217/39a58916-a1fc-11e6-82a6-7361e3844ec1.png)

You should also check you have linked model with its schema
![image](https://cloud.githubusercontent.com/assets/10420662/19975267/60780c80-a1fc-11e6-9714-b7e44a09693c.png)

Let me know if it helps

**Comment by neomerx** [comment]
I've added additional checks for input parameters such as table name and primary key so it would be easier to spot the issue earlier.

**Comment by ghost** [comment]
Full UserEntry Model:
<?php namespace App\Database\Models;

use App\Database\Types\DateTimeType;
use Doctrine\DBAL\Types\Type;
use Limoncello\JsonApi\Models\RelationshipTypes;

/**
- Class UserEntry
- @package App\Database\Models
  */
  class UserEntry extends Model
  {
  const TABLE_NAME = 'user_entries';
  const FIELD_ID = 'id_user_entry';
  
  const
      REL_USER = 'user';
  
  const
      FIELD_ID_USER = User::FIELD_ID;
  
  const
      FIELD_DESCRIPTION = 'description';
  
  /**
  - @return array
    */
    public static function getAttributeTypes()
    {
    return [
        self::FIELD_ID                      => Type::INTEGER,
        self::FIELD_ID_USER                 => Type::INTEGER,
        self::FIELD_DESCRIPTION             => Type::TEXT,
        self::FIELD_DISPLAY_ORDER           => Type::INTEGER,
        self::FIELD_CREATED_AT              => DateTimeType::NAME,
        self::FIELD_UPDATED_AT              => DateTimeType::NAME,
    ];
    }
  
  /**
  - @return array
    */
    public static function getAttributeLengths()
    {
    return [];
    }
  
  /**
  - @return array
    */
    public static function getRelationships()
    {
    return [
        RelationshipTypes::BELONGS_TO => [
            self::REL_USER                 => [User::class, self::FIELD_ID_USER, User::REL_USER_ENTRIES],
        ],
    ];
    }
    }

Full UserEntrySchema:

<?php namespace App\Schemes;

use App\Database\Models\UserEntry as Model;

/**
- Class UserEntrySchema
- @package App\Schemes
  */
  class UserEntrySchema extends BaseSchema
  {
  const TYPE = 'user-entries';
  const MODEL = Model::class;
  
  const
      REL_USER = Model::REL_USER;
  
  const
      ATTR_DESCRIPTION = Model::FIELD_DESCRIPTION;
  
  /**
  - @return array
    */
    public static function getMappings()
    {
    return [
        self::SCHEMA_ATTRIBUTES => [
            self::ATTR_DESCRIPTION   => Model::FIELD_DESCRIPTION,
            self::ATTR_CREATED_AT    => Model::FIELD_CREATED_AT,
            self::ATTR_UPDATED_AT    => Model::FIELD_UPDATED_AT,
        ],
        self::SCHEMA_RELATIONSHIPS => [
            self::REL_USER       => Model::REL_USER,
        ],
    ];
    }
    }

<?php namespace App\Database\Models;

use App\Database\Types\DateTimeType;
use Doctrine\DBAL\Types\Type;
use Limoncello\JsonApi\Models\RelationshipTypes;

class User extends Model
{
    const TABLE_NAME = 'users';
    const FIELD_ID = 'id_user';

```
const
    REL_ROLE = 'role';

const
    REL_USER_ENTRIES = 'user_entries',
    REL_POSTS = 'posts',
    REL_COMMENTS = 'comments';

const
    FIELD_ID_ROLE = Role::FIELD_ID;

const
    FIELD_NAME = 'name',
    FIELD_EMAIL = 'email',
    FIELD_PASSWORD_HASH = 'password_hash',
    FIELD_API_TOKEN = 'api_token',
    FIELD_DESCRIPTION = 'description';

const
    MIN_FIELD_PASSWORD = 6;

public static function getAttributeTypes()
{
    return [
        self::FIELD_ID             => Type::INTEGER,
        self::FIELD_ID_ROLE        => Type::INTEGER,
        self::FIELD_NAME           => Type::STRING,
        self::FIELD_EMAIL          => Type::STRING,
        self::FIELD_PASSWORD_HASH  => Type::STRING,
        self::FIELD_API_TOKEN      => Type::STRING,
        self::FIELD_DESCRIPTION    => Type::TEXT,
        self::FIELD_CREATED_AT     => DateTimeType::NAME,
        self::FIELD_UPDATED_AT     => DateTimeType::NAME,
    ];
}

/**
 * @return array
 */
public static function getAttributeLengths()
{
    return [
        self::FIELD_NAME          => 255,
        self::FIELD_EMAIL         => 255,
        self::FIELD_PASSWORD_HASH => 255,
        self::FIELD_API_TOKEN     => 255,
    ];
}

/**
 * @return array
 */
public static function getRelationships()
{
    return [
        RelationshipTypes::BELONGS_TO => [
            self::REL_ROLE        => [Role::class, self::FIELD_ID_ROLE, Role::REL_USERS],            ],
        RelationshipTypes::HAS_MANY => [
            self::REL_USER_ENTRIES               => [UserEntry::class, UserEntry::FIELD_ID, UserEntry::REL_USER],
            self::REL_POSTS                      => [Post::class, Post::FIELD_ID_BOARD, Post::REL_USER],
            self::REL_COMMENTS                   => [Comment::class, Comment::FIELD_ID_USER, Comment::REL_USER],
        ],
    ];
}
```

}

Full UserSchema:

<?php namespace App\Schemes;

use App\Database\Models\User as Model;

/**
- Class UserSchema
- @package App\Schemes
  */
  class UserSchema extends BaseSchema
  {
  const TYPE = 'users';
  const MODEL = Model::class;
  
  const
      REL_ROLE = Model::REL_ROLE;
  
  const
      REL_USER_ENTRIES = 'user-entries',
      REL_POSTS = Model::REL_POSTS,
      REL_COMMENTS = Model::REL_COMMENTS;
  
  const
      ATTR_NAME = Model::FIELD_NAME,
      ATTR_EMAIL = Model::FIELD_EMAIL;
  
  const V_ATTR_PASSWORD = 'password';
  const CAPTURE_NAME_PASSWORD = self::V_ATTR_PASSWORD;
  
  const
      ATTR_DESCRIPTION = Model::FIELD_DESCRIPTION;
  
  /**
  - @return array
    */
    public static function getMappings()
    {
    return [
        self::SCHEMA_ATTRIBUTES => [
            self::ATTR_NAME          => Model::FIELD_NAME,
            self::ATTR_EMAIL         => Model::FIELD_EMAIL,
    
    ```
        self::V_ATTR_PASSWORD    => self::CAPTURE_NAME_PASSWORD,
    
        self::ATTR_DESCRIPTION   => Model::FIELD_DESCRIPTION,
        self::ATTR_CREATED_AT    => Model::FIELD_CREATED_AT,
        self::ATTR_UPDATED_AT    => Model::FIELD_UPDATED_AT,
    ],
    self::SCHEMA_RELATIONSHIPS => [
        self::REL_ROLE               => Model::REL_ROLE,
        self::REL_USER_ENTRIES       => Model::REL_USER_ENTRIES,
        self::REL_POSTS              => Model::REL_POSTS,
        self::REL_COMMENTS           => Model::REL_COMMENTS,
    ],
    ```
    
    ];
    }
    }

**Comment by ghost** [comment]
checked that TABLE_NAME was presented.

**Comment by neomerx** [comment]
I will try to replicate the sample from the parts above however it would be easier if you published a project that reproduces the error. No need for the whole real project. Just the minimal part.

**Comment by neomerx** [comment]
What confuses me in your log is this line

>  An exception occurred while executing 'INSERT INTO (, created_at) VALUES(?, ?)' with params ["1", "2016-11-02 11:53:49"]

Absence of table name. It does not have even quotes however [source code for inserts](https://github.com/limoncello-php/json-api/blob/master/src/Adapters/Repository.php#L246) ([and this one](https://github.com/limoncello-php/json-api/blob/master/src/Adapters/Repository.php#L145) as well) says it must have at least quotes even if table name is empty. This source is master and it's tagged as 0.2.1. Is it possible you do not use latest version?

**Comment by neomerx** [comment]
Another thing I've spotted in your code you mistakenly uses `HAS_MANY` instead of `BELONGS_TO_MANY` for `user-entries` relationship. You can find a usage example [here](https://github.com/limoncello-php/json-api/blob/master/tests/Data/Models/Comment.php#L91-L98).
I believe that's the reason of the error. I'll think how it could be diagnosed earlier so the package would throw meaningful exception in such case.

**Comment by ghost** [comment]
but the users and user-entries are a one-to-many relationship.
is it correct to use belongs-to-many as the relationship?

**Comment by neomerx** [comment]
If so it's incorrect to save such entries while creating new user. How is this possible you already have user entries but do not have the user? You should create user and then create user entries. Otherwise what it should mean then? It looks like belongsToMany relationship.

```
                "user-entries": {
                    "data": [
                        { "type": "user-entries", "id": "1" },
                        { "type": "user-entries", "id": "2" }
                    ]
                }
```

I've added code which would check that every belongsTo must have hasMany on the other side and vice versa. It will help to quicker identify such issues.

**Comment by neomerx** [comment]
Also I believe it should be

``` php
    self::REL_USER_ENTRIES => [UserEntry::class, UserEntry::FIELD_ID_USER, UserEntry::REL_USER],
```

but not `UserEntry::FIELD_ID`

**Comment by neomerx** [comment]
You also send in input `user-status` which do not have any corresponding relationship neither in Schema nor in Model. I believe it should JsonApiException on validation for non-existing relationships. Well at least latest version should do which for some reason is not the case for your installation. Hmm...
