### ISSUE TITLE
composer test-unit with phpdbg result in "PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted"

### ISSUE THREAD

**Issue by dreamsbond** [limoncello-php/app#20]
I am currently experiencing a problem while running composer test-unit which was running 
"phpdbg -qrr ./vendor/bin/phpunit --coverage-text"

it results in 
[PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 65536 bytes) in /limoncello-php/vendor/limoncello-php/core/src/Reflection/ClassIsTrait.php on line 145]
[PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 65536 bytes) in /limoncello-php/vendor/limoncello-php/application/src/Packages/Application/Application.php on line 242]

**Comment by neomerx** [comment]
You should update memory limit for PHP in `php.ini`
```php.ini
memory_limit = -1
```
