### ISSUE TITLE
managing scopes via database level (idea)

### ISSUE THREAD

**Issue by dreamsbond** [limoncello-php/app#22]
i am thinking if it would be good to manage (crud) scopes via database level.

as adding new scope require assignScope with constant define in passport settings and seed it in passport seed.

what do you think?

**Comment by neomerx** [comment]
I don't fully understand what do you mean by 'manage scopes via database level.'
Passport has an API that works with a database with CRUD support. `create` is used in the seeder.

**Comment by dreamsbond** [comment]
I mean putting the way of assigning scope not only by seeder, but by some endpoint like '/scope' to manipulate the crud action

**Comment by neomerx** [comment]
I actually have it implemented in and it's not difficult to do. However, it requires adding JSON API Schemes and HTTP entry points not defined by the OAuth spec and some authorization rules that are also application specific. Many things that really are not related.
I thought of adding it to default application however due to those factors I had a feeling it would be too much opinionated code int the default application.

**Comment by neomerx** [comment]
I've added it to `Ideas` section https://github.com/neomerx/limoncello-flute/projects/1

**Comment by neomerx** [comment]
@dreamsbond However I would it a go as console commands. I would accept a PR from you to limoncello framework with CRUD commands for OAuth Clients (+Redirect URIs) and Scopes.
As a console command, it has no requirements to JSON API, HTTP entry points, and authorization (assuming only admins can run it). So it's much easier implement.

**Comment by neomerx** [comment]
that's an example of a command that does migration and seeding https://github.com/limoncello-php/framework/blob/master/components/Application/src/Commands/DataCommand.php
and that's the way to register it https://github.com/limoncello-php/framework/blob/master/components/Application/src/Packages/Application/ApplicationProvider.php#L42-L48

**Comment by neomerx** [comment]
Let me know if you try to add it. I can provide you with more assistance.

**Comment by dreamsbond** [comment]
Noted. I will try to add it.

**Comment by neomerx** [comment]
Role-Scopes link is outside of this scope. It's very app specific. I've added some basic role-based auth system to give a perspective of how it works so people can adopt it for their own needs.
