### ISSUE TITLE
relationship record were not protected

### ISSUE THREAD

**Issue by dreamsbond** [limoncello-php/app#28]
@neomerx i just found issues, not sure if it is.

for general usage, all resources are protected by the authorization rules accordingly

but i found in case of checking out the relationship 
say http://localhost:8088/api/v1/users/34/relationships/posts

the protection was bypassed, and without any unauthorized exception return

**Comment by neomerx** [comment]
Added authorization checks in reading relationships. Changes in 1 commit so you can see how to adapt it to your application.

**Comment by dreamsbond** [comment]
@neomerx i see, it wasn't an issue. only an application logic.
i didn't think of having such implementation before for relationship.
thanks
