### ISSUE TITLE
assert(static::isValidType($value) === true)

### ISSUE THREAD

**Issue by dreamsbond** [limoncello-php/app#30]
@neomerx i am refactoring my existing validation to your new ruleset style.
having problem doing test:

assert(): assert(static::isValidType($value) === true) failed

i have no idea yet. any glue?

**Comment by neomerx** [comment]
This is an assertion within `Validation` library. It is used in multiple places but all for checking input value is a `scalar`.
Most likely you're trying to use a validation rule for a `scalar` (e.g. bool, int, float, string, etc) with non-scalar input (e.g. array, DateTime or null). Can you debug the line and see what is inside `$value`?

**Comment by dreamsbond** [comment]
it was string string(5) "users" on var_dump($value)

**Comment by neomerx** [comment]
Hmmm.... "users" is a scalar so assert(is_scalar("users") === true) must be pass without problems. Are you sure it fails with this input?

**Comment by dreamsbond** [comment]
yes it all returns string...
let me check again

**Comment by neomerx** [comment]
let me know if you still have this issue and it needs to be re-opened.
