### ISSUE TITLE
Sorting relationship only works with Filtering

### ISSUE THREAD

**Issue by dreamsbond** [limoncello-php/app#37]
i got an error while performing relationship sorting:
query = /api/v1/users?sort=role.id
``` "status": "500",
            "title": "An exception occurred while executing 'SELECT `users1`.`id_user`, `users1`.`id_role`, `users1`.`first_name`, `users1`.`last_name`, `users1`.`email`, `users1`.`password_hash`, `users1`.`created_at`, `users1`.`updated_at`, `users1`.`deleted_at` FROM `users` `users1` INNER JOIN `roles` `roles2` ON `users1`.`id_role`=`roles2`.`id_role` WHERE () GROUP BY `users1`.`id_user` ORDER BY `roles2`.`id_role` ASC LIMIT 21 OFFSET 0':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') GROUP BY `users1`.`id_user` ORDER BY `roles2`.`id_role` ASC LIMIT 21 OFFSET 0' at line 1",
```

while 

query = api/v1/users?sort=-role.id&filter[role.id][in]=admin,moderator,user

correctly returns collection

**Comment by neomerx** [comment]
0.7.x or 0.8.x?

**Comment by dreamsbond** [comment]
framework ^0.8.0

**Comment by dreamsbond** [comment]
the where clause was ()

**Comment by neomerx** [comment]
Should be closed in the latest update. Plz make sure you have deleted `vendor` folder before the update.

**Comment by dreamsbond** [comment]
yes. the issue was fixed.

**Comment by dreamsbond** [comment]
i saw the operator '=' was no longer usable, instead operator 'eq' was mandatory, is operator '=' obsolete now?

**Comment by neomerx** [comment]
Not at all
'=' supported with 'eq'. Here is the [code for mapping](https://github.com/limoncello-php/framework/blob/master/components/Flute/src/Http/Query/ParametersMapper.php#L419-L473)
It might be an issue with encoding where '=' is actually send as '%3D' though

**Comment by neomerx** [comment]
I've tested both 'equals' and '=' and they work just fine. If you believe the bug exists I need you to send a description how to reproduce it
![image](https://user-images.githubusercontent.com/10420662/32531733-a62583ca-c456-11e7-9c37-389ae2f607ff.png)

**Comment by neomerx** [comment]
I deleted the previous post as this issue needs a bit more time to look into

**Comment by neomerx** [comment]
if request sent as `{{server}}/api/v1/boards?filter[id][=]=1` then PHP itself parses it as this
![image](https://user-images.githubusercontent.com/10420662/32531983-06b2fc4e-c458-11e7-8684-fb9c5f63ce91.png)
I believe in order PHP to parse it as we expect it should be URL encoded which I'm going to check

**Comment by neomerx** [comment]
Yep, that's the issue. If you URL encode it before and send `{{server}}/api/v1/boards?filter[id][%3D]=1` it will work just fine
![image](https://user-images.githubusercontent.com/10420662/32532047-900dfd18-c458-11e7-9377-980267ce5c41.png)

![image](https://user-images.githubusercontent.com/10420662/32532084-d0626f66-c458-11e7-9804-60985e5cddd5.png)

**Comment by dreamsbond** [comment]
> Not at all
> '=' supported with 'eq'. Here is the code for mapping
> It might be an issue with encoding where '=' is actually send as '%3D' though

ya. personally, i prefer eq over '=' as what you said of '%3D' issue :)
