### ISSUE TITLE
[PHP 7.2] count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by dreamsbond** [limoncello-php/app#38]
There was a error statement in nginx log stating

```
 "PHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /srv/www/limoncello-app/vendor/limoncello-php/core/src/Application/Application.php on line 442" while reading response header from upstream
```
It should be fine running limoncello app as observed, but would like to know if it should be ignore at anytime.

**Comment by neomerx** [comment]
it should check for `null` before calling `count`

```php
    private function createMiddlewareChainImpl(
        Closure $handler,
        PsrContainerInterface $container,
        array $middleware = null
    ): Closure {
        $start = count($middleware) - 1;
        for ($index = $start; $index >= 0; $index--) {
            $handler = $this->createMiddlewareChainLink($handler, $middleware[$index], $container);
        }

        return $handler;
    }
```

**Comment by neomerx** [comment]
hmm.... strangely but on my machine, it's totally OK to call `count` on `null`
![image](https://user-images.githubusercontent.com/10420662/32774506-8e2f1268-c93d-11e7-945f-e1366e5fc45d.png)

Can you try to change the code to the following and check if it fixes the issue on your machine? What PHP version do you use?

```php
    private function createMiddlewareChainImpl(
        Closure $handler,
        PsrContainerInterface $container,
        array $middleware = null
    ): Closure {
        if (empty($middleware) === false) {
            $start = count($middleware) - 1;
            for ($index = $start; $index >= 0; $index--) {
                $handler = $this->createMiddlewareChainLink($handler, $middleware[$index], $container);
            }
        }

        return $handler;
    }
```

**UPD** the PHP [documentatino](http://php.net/manual/en/function.count.php) also says it's OK to call it on `null`. Can you please look closer what input causes the error?

**UPD2** NO NEED to try the code. I've tested it on PHP7.2 and can confirm it will fix this PHP incompatibility.

**Comment by neomerx** [comment]
It looks you're using 7.2
[Upgrading notes say](https://github.com/php/php-src/blob/php-7.2.0RC4/UPGRADING)
> count() now raises a warning when an invalid parameter is passed.
Only arrays and objects implementing the Countable interface should be passed.

so `null` no longer a valid input

**Comment by neomerx** [comment]
This issue is a part of a bigger issue with testing tools. They are just not ready yet for PHP 7.2.
For example, if I run tests for one of the components `Mockery` fails with the same error. So it's not possible to run the test on PHP 7.2 at the moment.

```
Runtime:       PHP 7.2.0RC6
Configuration: /app/phpunit.xml

E...EEEE...E..EEEE.....................EEEE..............E....... 65 / 93 ( 69%)
EEEEEEE...........E........E                                      93 / 93 (100%)

Time: 139 ms, Memory: 14.00MB

There were 24 errors:

1) Limoncello\Tests\Application\Authorization\AuthorizationManagerTest::testTraitWrappers
count(): Parameter must be an array or an object that implements Countable

/app/vendor/mockery/mockery/library/Mockery/Expectation.php:313
/app/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:173
/app/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:138
/app/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:91
/app/src/Authorization/AuthorizationRulesTrait.php:115
/app/src/Authorization/AuthorizationRulesTrait.php:127
/app/tests/Authorization/AuthorizationManagerTest.php:77
```

**Comment by neomerx** [comment]
My bad :smile: I've updated mockery and it seems to work fine now.

```
PHPUnit 6.4.4 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.0RC6
Configuration: /app/phpunit.xml

................................................................. 65 / 93 ( 69%)
............................                                      93 / 93 (100%)

Time: 157 ms, Memory: 16.00MB

OK (93 tests, 304 assertions)
```

I'll check all the components on PHP 7.2

**Comment by dreamsbond** [comment]
oh sorry, my bad.
i recently upgraded to 7.2

**Comment by dreamsbond** [comment]
should i downgrade to 7.1 for the time being, somehow a same testing environment?

**Comment by dreamsbond** [comment]
the warning was gone, just tested

**Comment by neomerx** [comment]
That was the only place where the code was incompatible with PHP 7.2. All the rest is totally fine with PHP 7.2. I've just pushed the fix to github and it will become part of the release soon.

So you can change that only piece of code and wait for the next release.
