### ISSUE TITLE
How to authenticate requests?

### ISSUE THREAD

**Issue by dreamsbond** [limoncello-php/app#4]
tested that action canManageUsers keep returning null via getCurrentUserIdentity($context) and keep returning false via hasScope method
while implementing isOwner method to check against the ownership of user during editing

**Comment by neomerx** [comment]
Hi,

- make sure you've got the latest version of both application and the framework.
- add breakpoint/var_dump/etc at `\App\Authorization\UserRules::canManageUsers`.
- run test `\Tests\UserApiTest::testDelete`.

![image](https://user-images.githubusercontent.com/10420662/26883165-03b8d8a0-4ba5-11e7-808d-2f6dc5e9a96c.png)

**Comment by neomerx** [comment]
Don't forget to send authentication header/token with your requests. Without the token, your requests will not be authenticated and therefore some actions might not be authorized.

**Comment by dreamsbond** [comment]
hi,

yes i do send proper authentication header/token with my request and returning authorization "access_token".

![image](https://user-images.githubusercontent.com/26112605/26909066-03e2dbfa-4c31-11e7-9611-a4eff92f484e.png)

The problem was in create and update, specifically in Users, index and read in Users were fine. Posts, Comments and Boards were all just fine.

![image](https://user-images.githubusercontent.com/26112605/26909128-5dccad9e-4c31-11e7-93ee-db9b9a0a92c5.png)

![image](https://user-images.githubusercontent.com/26112605/26909129-69c0dc9c-4c31-11e7-9488-22c14f7427bc.png)

![image](https://user-images.githubusercontent.com/26112605/26909144-7c6d3886-4c31-11e7-9f9d-6792d43af19f.png)

![image](https://user-images.githubusercontent.com/26112605/26909202-d96ec22a-4c31-11e7-9561-fe62e95998a8.png)

![image](https://user-images.githubusercontent.com/26112605/26909277-4629a420-4c32-11e7-985c-27aa5c8faae7.png)

The problems was found in create and update of Users:
![image](https://user-images.githubusercontent.com/26112605/26909304-68ada4ec-4c32-11e7-9fc3-1308f14522f9.png)

![image](https://user-images.githubusercontent.com/26112605/26909312-7dedc2b0-4c32-11e7-90ef-e5648f174973.png)

![image](https://user-images.githubusercontent.com/26112605/26909322-8c4f709c-4c32-11e7-85f3-8e250bd30f5b.png)

![image](https://user-images.githubusercontent.com/26112605/26909339-a84f33f4-4c32-11e7-9b1c-e3f233dd3d5d.png)

![image](https://user-images.githubusercontent.com/26112605/26909346-b6f5b694-4c32-11e7-87f7-9727440e5ccb.png)

running test, hasScope via create return true, which works:

root@cfa0103a6ee6:limoncello-php# ./vendor/bin/phpunit --filter testCreate ./tests/UserApiTest.php
PHPUnit 5.7.20 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.0.18
Configuration: limoncello-php/phpunit.xml

.                                                                   1 / 1 (100%)bool(true)
bool(true)
bool(true)


Time: 817 ms, Memory: 12.00MB

OK (1 test, 7 assertions)

and also hasScope via update return true as well:


root@cfa0103a6ee6:limoncello-php# ./vendor/bin/phpunit --filter testUpdate ./tests/UserApiTest.php
PHPUnit 5.7.20 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.0.18
Configuration: /limoncello-php/phpunit.xml

.                                                                   1 / 1 (100%)bool(true)
bool(true)
bool(true)


Time: 960 ms, Memory: 12.00MB

OK (1 test, 11 assertions)

**Comment by dreamsbond** [comment]
running UsersApiTest with injecting var_dump in canManageUsers of UsersRule does return true;
but postman on create user keep returning false;

OK (6 tests, 38 assertions)
root@cfa0103a6ee6:/limoncello-php# ./vendor/bin/phpunit ./tests/UserApiTest.php
PHPUnit 5.7.20 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.0.18
Configuration: /limoncello-php/phpunit.xml

...bool(true)
.bool(true)
.bool(true)
.                                                              6 / 6 (100%)

Time: 1.63 seconds, Memory: 14.00MB

OK (6 tests, 38 assertions)

![image](https://user-images.githubusercontent.com/26112605/26929867-d39d9874-4c8d-11e7-8417-99da43d90eec.png)

**Comment by neomerx** [comment]
@dreamsbond so the problem is that create/update users works in tests but fails with Postman, right?

**Comment by dreamsbond** [comment]
@neomerx  yes

**Comment by neomerx** [comment]
@dreamsbond make sure you do not have any extra spaces between 'Bearer' and token value. It must be exactly one space.
Though the app should correctly respond to such invalid requests with 401 code.

I just tried to create a user from Postman and it worked fine.

1 receive token
![image](https://user-images.githubusercontent.com/10420662/26974905-1f737316-4d26-11e7-89aa-e9f4b9f245c2.png)

2 send POST user with the token and JSON body
![image](https://user-images.githubusercontent.com/10420662/26974933-4652552e-4d26-11e7-999a-57e282e3453b.png)
![image](https://user-images.githubusercontent.com/10420662/26974953-5bd8ce50-4d26-11e7-8f78-074df07b7c3c.png)

**Comment by dreamsbond** [comment]
@neomerx i would like to ask, what will happen if a same user login twice or above?
there they got two tokens

**Comment by neomerx** [comment]
@dreamsbond Yes, if you request 2 tokens you will get 2 tokens.

**Comment by dreamsbond** [comment]
@neomerx i am sure i have latest commit checked out. but to ensure if i got something wrong. i have checkout . again and composer l:db rollback && composer l:db migrate && l:db seed again to make everything in original state. and i double checked if i got unwanted space in putting the access_token in request. the result was "yes", it works now !!

**Comment by neomerx** [comment]
@dreamsbond I just pushed changes addressing the issue with double space you had. The app should behave more consistently and return 401 HTTP error for an invalid token.
