### ISSUE TITLE
Controller readRelationship

### ISSUE THREAD

**Issue by dreamsbond** [limoncello-php/app#52]
having read the readRelationship, to my understanding.
looks like it get relationship data directly without pass through the api authorization.

```php
    protected static function readRelationship(
        string $index,
        string $modelRelName,
        string $queryValRulesClass,
        ContainerInterface $container,
        ServerRequestInterface $request
    ): ResponseInterface {
        static::assertClassValueDefined(static::API_CLASS);
        static::assertClassValueDefined(static::SCHEMA_CLASS);

        $api     = static::defaultCreateApi($container, static::API_CLASS);
        $handler = function () use ($api, $index, $modelRelName) {
            return $api->readRelationship($index, $modelRelName);
        };

        return static::defaultReadRelationshipWithClosureHandler(
            $handler,
            $request->getQueryParams(),
            $request->getUri(),
            static::defaultCreateQueryParser($container, $queryValRulesClass),
            static::defaultCreateParameterMapper($container, static::SCHEMA_CLASS),
            $api,
            $container->get(SettingsProviderInterface::class),
            $container->get(JsonSchemasInterface::class),
            $container->get(EncoderInterface::class)
        );
    }
```

if i got to restrict the access of a resource, how do i make it?

**Comment by neomerx** [comment]
Default low level API methods do not call auth by themselves. You as a developer to decide where you need auth and what kind of and where you don't.

I recommend adding a method to API such as `readPutYourRelationshipNameHere` and add auth check there. Here is an [example](https://github.com/limoncello-php/app/blob/9da46f0bf739f49a37540500b40f55143bf3d0cd/server/app/Api/PostsApi.php#L90-L98)

**Comment by dreamsbond** [comment]
Yes but seems authorizer there does not have effect

**Comment by neomerx** [comment]
Can you please provide an example?

**Comment by neomerx** [comment]
Add a breakpoint in the policy to make sure you actually call it and try to return `false`.
