### ISSUE TITLE
Does limoncello support NoSQL, like mongoDB?

### ISSUE THREAD

**Issue by dreamsbond** [limoncello-php/app#59]
Curious if limoncello supports mongoDB.

**Comment by neomerx** [comment]
Limoncello uses DBAL to work with databases. A list of supported databases by DBAL is [here](https://www.doctrine-project.org/projects/doctrine-dbal/en/2.9/reference/platforms.html). Thus, if you have [MongoDB](https://www.php.net/manual/en/set.mongodb.php) installed you can either use it directly or with a wrapper such as [Doctrine MongoDB](https://github.com/doctrine/mongodb).

Technically, it would be better to place either of them to the application container [as shown here](https://github.com/limoncello-php/app/tree/master/server/app/Container) and use it anywhere in the app.

For example,

```php
class MongoDbConfigurator implements ContainerConfiguratorInterface
{
    public static function configureContainer(LimoncelloContainerInterface $container): void
    {
        $container[\MongoDB\Driver\Manager::class] = function (PsrContainerInterface $container) {
            // read MongoDB settings (e.g. connect string and etc)
            $settings = $container->get(SettingsProviderInterface::class)->get(\Settings\MongoDB::class);
            
            // create MongoDB connection with settings
            return new \MongoDB\Driver\Manager(...);
        };
    }
}
```

**Comment by dreamsbond** [comment]
Thanks!
